---
title: "Learning"
author: "Scary Scarecrow"
date: "7/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(raster)
library(reticulate)
library(osmdata)
```

## R Markdown


```{r}
name <- LETTERS[1:10]
longitude <- c(-116.7, -120.4, -116.7, -113.5, -115.5,
               -120.8, -119.5, -113.7, -113.7, -110.7)
latitude <- c(45.3, 42.6, 38.9, 42.1, 35.7, 38.9,
              36.2, 39, 41.6, 36.9)
stations <- cbind(longitude, latitude)
# Simulated rainfall data
set.seed(0)
precip <- round((runif(length(latitude))*10)^3)
psize <- 1 + precip/500
```


```{r}
plot(stations, cex=psize, pch=20, col='red', main='Precipitation')
# add names to plot
text(stations, name, pos=4)
# add a legend
breaks <- c(100, 250, 500, 1000)
legend.psize <- 1+breaks/500
legend("topright", legend=breaks, pch=20, pt.cex=legend.psize, col='red', bg='gray')
```



```{r}
lon <- c(-116.8, -114.2, -112.9, -111.9, -114.2, -115.4, -117.7)
lat <- c(41.3, 42.9, 42.4, 39.8, 37.6, 38.3, 37.6)
x <- cbind(lon, lat)
plot(stations, main='Precipitation')
polygon(x, col='blue', border='light blue')
lines(stations, lwd=3, col='red')
points(x, cex=2, pch=20)
points(stations, cex=psize, pch=20, col='red', main='Precipitation')
```



```{r}
lonlat <- cbind(longitude, latitude)
pts <- SpatialPoints(lonlat)
class (pts)
showDefault(pts)
crdref <- CRS('+proj=longlat +datum=WGS84')
pts <- SpatialPoints(lonlat, proj4string=crdref)
pts
precipvalue <- runif(nrow(lonlat), min=0, max=100)
df <- data.frame(ID=1:nrow(lonlat), precip=precipvalue)
ptsdf <- SpatialPointsDataFrame(pts, data=df)
ptsdf
str(ptsdf)

lon <- c(-116.8, -114.2, -112.9, -111.9, -114.2, -115.4, -117.7)
lat <- c(41.3, 42.9, 42.4, 39.8, 37.6, 38.3, 37.6)
lonlat <- cbind(lon, lat)
lns <- spLines(lonlat, crs=crdref)
lns

pols <- spPolygons(lonlat, crs=crdref)
pols
str(pols)
```



```{r}
plot(pols, axes=TRUE, las=1)
plot(pols, border='blue', col='yellow', lwd=3, add=TRUE)
points(pts, col='red', pch=20, cex=3)
```


```{r}
r <- raster(ncol=10, nrow=10, xmx=-80, xmn=-150, ymn=20, ymx=60)
r
values(r) <- runif(ncell(r))
r
values(r) <- 1:ncell(r)
r
plot(r)
# add polygon and points
lon <- c(-116.8, -114.2, -112.9, -111.9, -114.2, -115.4, -117.7)
lat <- c(41.3, 42.9, 42.4, 39.8, 37.6, 38.3, 37.6)
lonlat <- cbind(lon, lat)
pols <- spPolygons(lonlat, crs='+proj=longlat +datum=WGS84')
points(lonlat, col='red', pch=20, cex=3)
plot(pols, border='blue', lwd=2, add=TRUE)
```




```{r}
r2 <- r * r
r3  <- sqrt(r)
s <- stack(r, r2, r3)
s
plot(s)
b <- brick(s)
b
```


```{r}
x <- raster()
x <- raster(ncol=36, nrow=18, xmn=-1000, xmx=1000, ymn=-100, ymx=900)
x
res(x) <- 100
x
projection(x) <- "+proj=utm +zone=48 +datum=WGS84"
x
```


```{r}
b <- getbb ("ralegaon, yavatmal, maharashtra", format_out = "polygon")
b %>% 
  add_osm_feature(key = 'natural', value = 'water')

q<-opq(bbox = 'ralegaon, yavatmal, maharashtra') %>%
    add_osm_feature(key = 'natural', value = 'water')


  
 r<-osmdata_sp(q)
 sp::plot(r$osm_multipolygons)
 r$osm_polygons
 names(r$osm_polygons$water)<-NULL
 
 names(q$osm_polygons$geometry)<-NULL
 
  leaflet::leaflet() %>% 
  leaflet::addPolygons(q$osm_polygons)
   
  opq(bbox = 'ralegaon, yavatmal, maharashtra') %>%
    add_osm_feature(key = 'natural', value = 'water') %>%
    osmdata_xml(filename = 'mh_yav_ral.osm')
  
  dat<-sf::st_read('mh_yav_ral.osm', layer = 'multipolygons')
  
  dat_sp <- as(dat, 'Spatial')
  
  
  leaflet::leaflet(dat_sp) %>% 
    leaflet::addTiles() %>% 
    leaflet::addPolygons()
  
   
```
















